//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassCharacter
    {
        public short ClassCharacterId { get; set; }
        public byte ClassId { get; set; }
        public short CharacterId { get; set; }
        public Nullable<byte> ClassOrder { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Class Class { get; set; }
    }
}
