//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassNPC
    {
        public int ClassNpcId { get; set; }
        public Nullable<byte> ClassId { get; set; }
        public short NpcId { get; set; }
        public Nullable<byte> ClassOrder { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual NPC NPC { get; set; }
    }
}
