//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.LocaleEvents = new HashSet<LocaleEvent>();
            this.OrgEvents = new HashSet<OrgEvent>();
        }
    
        public short EventId { get; set; }
        public short InfoId { get; set; }
        public string Name { get; set; }
        public bool IsHistory { get; set; }
        public System.DateTime Date { get; set; }
        public string AboutText { get; set; }
        public string NormalParticipants { get; set; }
        public bool IsWorkInProgress { get; set; }
    
        public virtual Info Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocaleEvent> LocaleEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgEvent> OrgEvents { get; set; }
    }
}
