//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoTag
    {
        public int InfoTagId { get; set; }
        public short InfoId { get; set; }
        public short TagId { get; set; }
    
        public virtual Info Info { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
