//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lore
    {
        public short LoreId { get; set; }
        public short InfoId { get; set; }
        public string Name { get; set; }
        public string TheContent { get; set; }
        public bool IsWorkInProgress { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
