//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NPC()
        {
            this.ClassNPCs = new HashSet<ClassNPC>();
            this.Locales = new HashSet<Locale>();
            this.NpcOrgs = new HashSet<NpcOrg>();
        }
    
        public short NpcId { get; set; }
        public short InfoId { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Quote { get; set; }
        public string PortraitFileName { get; set; }
        public Nullable<byte> RaceId { get; set; }
        public string CrestFileName { get; set; }
        public string ApperanceText { get; set; }
        public string AboutText { get; set; }
        public Nullable<short> LastLocationId { get; set; }
        public bool IsWorkInProgress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassNPC> ClassNPCs { get; set; }
        public virtual Info Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locale> Locales { get; set; }
        public virtual Locale Locale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NpcOrg> NpcOrgs { get; set; }
        public virtual Race Race { get; set; }
    }
}
