//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NpcOrg
    {
        public short NpcOrgId { get; set; }
        public short NpcId { get; set; }
        public short OrgId { get; set; }
        public Nullable<byte> OrgOrder { get; set; }
        public string BlurbNpcPage { get; set; }
        public string BlurbOrgPage { get; set; }
        public bool IsCurrent { get; set; }
        public Nullable<byte> MemberOrder { get; set; }
    
        public virtual NPC NPC { get; set; }
        public virtual Org Org { get; set; }
    }
}
