//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiftWorldEntities : DbContext
    {
        public RiftWorldEntities()
            : base("name=RiftWorldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<CharOrg> CharOrgs { get; set; }
        public virtual DbSet<CharSecret> CharSecrets { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassCharacter> ClassCharacters { get; set; }
        public virtual DbSet<ClassNPC> ClassNPCs { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Info> Infos { get; set; }
        public virtual DbSet<InfoTag> InfoTags { get; set; }
        public virtual DbSet<InfoType> InfoTypes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<LocaleEvent> LocaleEvents { get; set; }
        public virtual DbSet<LocaleLevel> LocaleLevels { get; set; }
        public virtual DbSet<Locale> Locales { get; set; }
        public virtual DbSet<Lore> Lores { get; set; }
        public virtual DbSet<Majority> Majorities { get; set; }
        public virtual DbSet<NpcOrg> NpcOrgs { get; set; }
        public virtual DbSet<NPC> NPCs { get; set; }
        public virtual DbSet<OrgEvent> OrgEvents { get; set; }
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Rift> Rifts { get; set; }
        public virtual DbSet<Rumor> Rumors { get; set; }
        public virtual DbSet<Secret> Secrets { get; set; }
        public virtual DbSet<SecretSecretTag> SecretSecretTags { get; set; }
        public virtual DbSet<SecretTag> SecretTags { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<StoryTag> StoryTags { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Tier> Tiers { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<VarietyOfInhabitant> VarietyOfInhabitants { get; set; }
    }
}
