//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rumor
    {
        public int RumorsId { get; set; }
        public short RumorOfId { get; set; }
        public short AuthorId { get; set; }
        public bool IsApproved { get; set; }
        public string RumorText { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Info Info { get; set; }
    }
}
