//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecretSecretTag
    {
        public int SstId { get; set; }
        public short SecretId { get; set; }
        public short SecretTagId { get; set; }
    
        public virtual Secret Secret { get; set; }
        public virtual SecretTag SecretTag { get; set; }
    }
}
