//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Story()
        {
            this.StoryTags = new HashSet<StoryTag>();
        }
    
        public short StoryId { get; set; }
        public short IsAboutId { get; set; }
        public System.DateTime DateTold { get; set; }
        public string CommissionedBy { get; set; }
        public bool IsCannon { get; set; }
        public string TheContent { get; set; }
        public string Title { get; set; }
    
        public virtual Info Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoryTag> StoryTags { get; set; }
    }
}
