//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftWorld.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VarietyOfInhabitant
    {
        public short VarietyOfInhabitantsId { get; set; }
        public short RiftId { get; set; }
        public byte RaceId { get; set; }
        public Nullable<byte> RaceOrder { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual Rift Rift { get; set; }
    }
}
